name: to_do
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  foundation: ^0.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  curved_navigation_bar: ^1.0.3
  firebase_core: ^2.13.1
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.6.0
  provider: ^6.1.1
  convex_bottom_bar: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3


flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700

